setx "SQL_ADMINISTRATIVE_VIEWS_SUMMARY_Top_Cpu_Title" "CPU"
setx "SQL_ADMINISTRATIVE_VIEWS_SUMMARY_Top_Cpu_Kind" "String"
setx "SQL_ADMINISTRATIVE_VIEWS_SUMMARY_Top_Cpu_Value" "AMD Ryzen 7 5700G with Radeon Graphics"
setx "SQL_ADMINISTRATIVE_VIEWS_SUMMARY_Top_Cpu_Position" Header

:: setx "SQL_ADMINISTRATIVE_VIEWS_SUMMARY_1_RAM_Disk_Title" "Data RAM Disk (MB)"
:: setx "SQL_ADMINISTRATIVE_VIEWS_SUMMARY_1_RAM_Disk_Kind" "Natural"
:: setx "SQL_ADMINISTRATIVE_VIEWS_SUMMARY_1_RAM_Disk_Value" "3072"
:: setx "SQL_ADMINISTRATIVE_VIEWS_SUMMARY_1_RAM_Disk_Position" 999
